version: "3.7"

services:
  
  meilisearch:
    container_name: logme_meilisearch
    image: getmeili/meilisearch:latest
    networks:
      - app-network
    ports:
      - "7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true

  server:
    container_name: logme_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file: .env
    depends_on:
      - meilisearch
    links:
      - meilisearch
    networks:
      - app-network
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/github.com/patoui/logme

#Docker Networks
networks:
  app-network:
    driver: bridge
