version: "3.7"

services:
  server:
    container_name: logme_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file: .env
    depends_on:
      logs:
        condition: service_healthy
        restart: true
      database:
        condition: service_started
      meilisearch:
        condition: service_started
    links:
      - meilisearch
      - "logs:logme_clickhouse_database"
    networks:
      - app-network
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/github.com/patoui/logme

  logs:
    container_name: logme_clickhouse_database
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    networks:
      - app-network
    volumes:
      - ./docker/clickhouse/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 1s
      timeout: 5s
      retries: 10

  database:
    container_name: logme_postgres_database
    image: postgres
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssword321
    ports:
      - "5432:5432"
    networks:
      - app-network
    user: 999:999
    volumes:
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d

  meilisearch:
    container_name: logme_meilisearch
    image: getmeili/meilisearch:latest
    networks:
      - app-network
    ports:
      - "7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true

#Docker Networks
networks:
  app-network:
    driver: bridge
