services:
  server:
    container_name: logme_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file: .env
    depends_on:
      logs:
        condition: service_started
      database:
        condition: service_started
      cache:
        condition: service_started
      queue:
        condition: service_started
    networks:
      - app-network
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/github.com/patoui/logme

  logs:
    container_name: logme_clickhouse
    image: clickhouse/clickhouse-server:24.5.1-alpine
    ports:
      - 8123:8123
      - 9000:9000
      - 9009:9009
    networks:
      - app-network
    volumes:
      - ./docker/clickhouse/initdb:/docker-entrypoint-initdb.d

  database:
    container_name: logme_postgres
    image: postgres
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssword321
    ports:
      - "5432:5432"
    networks:
      - app-network
    user: 999:999
    volumes:
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d

  cache:
    container_name: logme_cache
    image: valkey/valkey:7.2-alpine3.19
    networks:
      - app-network

  queue:
    container_name: logme_queue
    build:
      context: .
      dockerfile: ./docker/queue/Dockerfile
    depends_on:
      - cache
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
