version: "3.7"

services:

  database:
    container_name: logme_database
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    networks:
      - app-network
    volumes:
      - ./docker/clickhouse/initdb:/docker-entrypoint-initdb.d

  server:
    container_name: logme_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - app-network
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/github.com/patoui/logme

#Docker Networks
networks:
  app-network:
    driver: bridge
